---
title: "Vietnam Leeches"
author: "Douglas Yu"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(vegan)
```

## Read data

```{r read data}
lowreadthreshold <- 100
inputfile <- c("allWWFWCS_BFCusearchMF_CROP98_otu_TAX20161217_20170305.xlsx")
leechidna <- read_excel(inputfile, sheet = "16Svert", skip = 1)
leechidna <- leechidna[ , 2:720] # can't use dplyr::select because some of the columns have duplicate names, and select can't handle that
names(leechidna)
leechidna <- leechidna %>% filter(Total_reads >= lowreadthreshold | Family %in% c("Manidae", "Lorisidae")) # filter out low-read OTUs but keep slow loris and pangolin

reserve <- read_excel(inputfile, sheet = "Site_codes")
names(reserve)
reserve <- reserve %>% select(Sample_16SVert_Row2, Reserve_StdName, Reserve_SubName, Approx_number_leeches)
```

```{r sum read numbers by taxonomy}
names(leechidna)
leechidna2 <- leechidna %>% group_by(OTUs_merged_by_taxonomy) %>% summarise_at(vars(WWF1:WWF465), sum)
names(leechidna2)
# leechidna2$OTUs_merged_by_taxonomy
```

```{r remove negative controls}
negctrls <- c("BM","H1s","H2s","H3s","Q1s","Q2s","Q3s","XS2","XS5","XS6","XS7","XS8","XS9","SWG1s","SWG2s","XS1s","XS2s","2015Dec")

leechidna3 <- leechidna2

for(i in 1:length(negctrls)) {
	leechidna3 <- leechidna3 %>% select(-starts_with(negctrls[i]))
}

# names(leechidna3)
# leechidna3 <- leechidna2 %>% select(-starts_with(neg[1]), -starts_with(neg[2]), -starts_with(neg[3]), -starts_with(neg[4]), -starts_with(neg[5]), -starts_with(neg[6]), -starts_with(neg[7]), -starts_with(neg[8]), -starts_with(neg[9]), -starts_with(neg[10]), -starts_with(neg[11]), -starts_with(neg[12]), -starts_with(neg[13]), -starts_with(neg[14]), -starts_with(neg[15]), -starts_with(neg[16]), -starts_with(neg[17]), -starts_with(neg[18])) # slow way
```

```{r filter by read number, eval=FALSE}
# if i want to set cells to 0 that have fewer reads than the negative controls for that batch of samples.  I haven't implemented it yet, but i have generated the negative control matrix.
leechidna_negctrls <- leechidna2
leechidna_samples <- colnames(leechidna3)
leechidna_negctrls <- leechidna_negctrls %>% select(-one_of(leechidna_samples))
# leechidna_negctrls
```


```{r add total_reads and incidence columns}
leechidna3$total_reads <- leechidna3 %>% select(-OTUs_merged_by_taxonomy) %>% rowSums()

leechidna3$incidence <- leechidna3 %>% select(-OTUs_merged_by_taxonomy, -total_reads) %>% specnumber(MARGIN=1)

# names(leechidna3)
# leechidna3$incidence
# leechidna3$total_reads
```


```{r filter by taxonomy}
# change OTU names to format that is acceptable to R as column names

leechidna3$OTUs_merged_by_taxonomy <- make.names(leechidna3$OTUs_merged_by_taxonomy)
leechidna3$OTUs_merged_by_taxonomy <- gsub("cf..", "cf_", leechidna3$OTUs_merged_by_taxonomy, fixed = TRUE) # fixed = T is to not use grep

# remove some taxa
taxa_to_remove <- c("Actinopterygii|Amphibia|Archelosauria|lab.contamination|laboratory.contamination")
leechidna4 <- leechidna3 %>% filter(!grepl(taxa_to_remove, OTUs_merged_by_taxonomy))
# leechidna4$OTUs_merged_by_taxonomy

# taxonomic subsets
leechidna_named_mammals <- leechidna4 %>% filter(!grepl(c("no.assignment|root"), OTUs_merged_by_taxonomy))

leechidna_carnivora <- leechidna4 %>% filter(grepl(c("Carnivora"), OTUs_merged_by_taxonomy))

leechidna_critters <- leechidna4 %>% filter(grepl(c("Rodentia|Scandentia|Lagomorpha|Insectivora|Pholidota"), OTUs_merged_by_taxonomy))

leechidna_cetartiodactyla <- leechidna4 %>% filter(grepl(c("Cetartiodactyla"), OTUs_merged_by_taxonomy))

leechidna_primates <- leechidna4 %>% filter(grepl(c("Primates"), OTUs_merged_by_taxonomy)) 
```

```{r transpose to community}
# create site X species tables
varNames <- c("named_mammals", "carnivora", "critters", "cetartiodactyla", "primates")

for (i in seq_along(varNames)) {
  d <- get(paste0("leechidna_", varNames[i])) # get a community subset
  d_t <- t(d) # transpose
  colnames(d_t) <- d_t[1,] # move taxonomic names to column names
  d_t <- as.data.frame(d_t) # coerce to dataframe
  d_t <- rownames_to_column(d_t, var = "site") # add site names to dataframe
  d_t <- d_t %>% filter(site != "OTUs_merged_by_taxonomy", site != "incidence", site != "total_reads") # filter out these rows
  assign(paste0("leechidna_", varNames[i], "_t"), d_t) # assign output to the correct object name
}
```

https://codedocean.wordpress.com/2014/01/14/r-working-with-named-objects-in-a-loop/

```{r create environment datasets}
varNames <- c("named_mammals", "carnivora", "critters", "cetartiodactyla", "primates")

# add a comment

for (i in seq_along(varNames)) {
  d <- get(paste0("leechidna_", varNames[i], "_t")) # get a community subset
  dreserve <- left_join(d, reserve, by = c("site" = "Sample_16SVert_Row2")) # use the site column to add environment data in correct order
  assign(paste0("OTU_by_Site_", varNames[i]), dreserve) # create site X species tables for outside use
  dreserve <- dreserve %>% select(site, Reserve_StdName, Approx_number_leeches) # choose the env columns
  assign(paste0("reserve_", varNames[i]), dreserve) # create object with correct name
  d <- d %>% select(-site)
  assign(paste0("leechidna_", varNames[i], "_t"), d)
}

# now that site column has been removed, convert the remaining OTU columns to numeric
# http://stackoverflow.com/questions/2288485/how-to-convert-a-data-frame-column-to-numeric-type
for (i in seq_along(varNames)) {
  d <- get(paste0("leechidna_", varNames[i], "_t")) # get a community subset
  d <- as.data.frame(sapply(d, function(x) as.numeric(as.character(x)))) 
  assign(paste0("leechidna_", varNames[i], "_t"), d)
}

# omit rows that have rowSums = 0, from both OTU and environment datsets
for (i in seq_along(varNames)) {
  d <- get(paste0("leechidna_", varNames[i], "_t")) # get a community subset
  r <- get(paste0("reserve_", varNames[i]))
  r <- r[which(rowSums(d) > 0), ]
  d <- d[which(rowSums(d) > 0), ]
  assign(paste0("leechidna_", varNames[i], "_t"), d)
  assign(paste0("reserve_", varNames[i]), r)
}

# change column orders of the site X species tables and write to disk
for (i in seq_along(varNames)) {
  otu <- get(paste0("OTU_by_Site_", varNames[i])) # get a community subset
  otu <- otu %>% select(Reserve_StdName, Reserve_SubName, Approx_number_leeches, everything()) # change the column orders
  otu <- otu %>% rename(ECEC_code = site)
  assign(paste0("OTU_by_Site_", varNames[i]), otu) # create object with correct name
  write.table(get(paste0("OTU_by_Site_", varNames[i])), file = paste0("OTU_by_Site_", varNames[i],".tsv"),sep ="\t", row.names = FALSE)
}

rm(otu)
rm(d)
rm(r)
rm(d_t)
rm(dreserve)
```


The community analyses aren't that interesting.  Need to do some filtering of samples before doing the analysis. (there are some serious outlier samples)

```{r community analysis}
varNames <- c("named_mammals", "carnivora", "critters", "cetartiodactyla", "primates")

i <- 1

community <- paste0("leechidna_", varNames[i], "_t") # get a community subset
reserve <- paste0("reserve_", varNames[i])

rowSums(get(community))
dca <- decorana(get(community))
tabasco(decostand(get(community), "log"), dca)

# p1 <- plot(community.jmds, dis="sites")
# identify(p1, "sites") # interactive method to identify sites by row number. Click on the points that you want to identify. When you have clicked on all the points, click on the Finish button at top right of Plot window. 
```

```{r basic NMDS plot}
community.jmds <- metaMDS(decostand(get(community), "log"), dist="jaccard")
plot(community.jmds, type = "t", scaling = 2)
community2.jmds <- metaMDS(get(community), dist="jaccard")
plot(community2.jmds, type = "t", scaling = 2)

plot(community.jmds, display="sites", type="n")
with(get(reserve),ordiellipse(community.jmds, Reserve_StdName, cex=.5, draw="polygon",col=c("blue"),alpha=10,kind="se",conf=0.95,label=FALSE, show.groups=(c("BachMaExt","BachMaNP", "SWG2015"))))
with(get(reserve),ordiellipse(community.jmds, Reserve_StdName, cex=.5, draw="polygon",col=c("green"),alpha=10,kind="se",conf=0.95,label=FALSE, show.groups=(c("HueSaoLaNR"))))
with(get(reserve),ordiellipse(community.jmds, Reserve_StdName, cex=.5, draw="polygon",col=c("yellow"),alpha=10,kind="se",conf=0.95,label=FALSE, show.groups=(c("XeSap"))))
with(get(reserve),ordiellipse(community.jmds, Reserve_StdName, cex=.5, draw="polygon",col=c("red"),alpha=10,kind="se",conf=0.95,label=FALSE, show.groups=(c("QuangNamSaoLaNR"))))
```

```{r cca plot}
community.ca <- cca(decostand(get(community), "log"))
community.ca
plot(community.ca, scaling = 1)
```

```{r decorana}
community.dca <- decorana(decostand(get(community), "log"))
community.dca
plot(community.dca, scaling = 3)
```

